version: "2.1"

services:
  oclclient:
    image: openmrs/ocl-client:qa
    environment:
      - OCL_API_HOST=${OCL_API_HOST:-https://api.qa.openconceptlab.org}
      - TRADITIONAL_OCL_HOST=${TRADITIONAL_OCL_HOST:-https://app.qa.openconceptlab.org}
      - OCL_SIGNUP_URL=${OCL_SIGNUP_URL:-https://app.qa.openconceptlab.org/#/accounts/signup}
      - OCL_GA_TOKENS=${OCL_GA_TOKENS}
      - ENVIRONMENT=${ENVIRONMENT:-qa}
    ports:
      - 8084:80
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sSf", "localhost"]
